const products = [
  {
    id: 1,
    shopId: 101,
    name: "Vive Stand Assist",
    categoryId: 1,
    description:
      "Providing safe, stable assistance, the Stand Assist by Vive allows individuals to rise from chairs, sofas and recliners with greater ease. The dual support handles create a stable foundation for pushing up to a standing position without twisting and turning, minimizing the risk of hazardous falls.",
    benefits: [
      "EASY INSTALLATION",
      "ADJUSTABLE FRAME",
      "COMFORTABLY SOFT GRIP COVERS",
    ],
    price: 50.0,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 2,
    shopId: 102,
    name: "Vive Bed Assist Rail",
    categoryId: 1,
    description:
      "Providing additional assistance when getting into or out of bed, the safety rail is stable and secure. The bed rail is held securely in place with a stabilizing bar and rubber tipped legs. The bed assist handle also folds flat for convenient storage.",
    benefits: [
      "NON-SLIP COMFORTABLE HANDLE",
      "EASY, TOOL-FREE ASSEMBLY",
      "USE WITH ANY BED",
    ],
    price: 80.0,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 3,
    shopId: 103,
    name: "Vive Car Handle Assist",
    categoryId: 1,
    description:
      "Providing stabilizing assistance, the Vive Car Assist Handle allows you to exit your car, truck or SUV independently. The strong support handle is ideal for the elderly, following surgery and for those with limited mobility or back pain.",
    benefits: [
      "COMFORT GRIP",
      "LIGHTWEIGHT & SCRATCH RESISTANT",
      "60 DAY WARRANTY",
    ],
    price: 17.0,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 4,
    shopId: 104,
    name: "Sock Aid Device for Seniors",
    categoryId: 2,
    description:
      "The sock aid device is designed with a plastic shell that can support nylon socks, cotton socks, stockings, and other short socks, making it easy to insert socks into the sock aid. Specially designed for people who cannot freely bend their bodies.",
    benefits: [
      "If you have difficulty bending, limited flexibility, or difficulty reaching, these tools can help you avoid this problem",
      "The sock remover adopts a telescopic design, which is convenient for your storage and carrying",
    ],
    price: 20.0,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 5,
    shopId: 105,
    name: "Stander EZ Stand-N-Go",
    categoryId: 3,
    description:
      "The Stander EZ Stand-N-Go is a standing frame with dual handles that assist users in standing easily and comfortably from a recliner, couch, or chair. The frame adjusts in height, width, and depth to fit a wide range of couches and chairs.",
    benefits: [
      "ADJUSTABLE HEIGHT, WIDTH, AND DEPTH",
      "EASY TO USE",
      "STABLE AND COMFORTABLE",
    ],
    price: 135.0,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 6,
    shopId: 106,
    name: "Stander Assist-A-Tray",
    categoryId: 4,
    description:
      "The Stander Assist-A-Tray Standing Aid is two products in one! This innovative mobility aid is designed to assist you getting in and out of your couch or chair as well as provide a convenient lap desk that swivels 360 degrees out of the way when it isn't in use.",
    benefits: ["TWO-IN-ONE FUNCTIONALITY", "SWIVEL LAP DESK", "STURDY DESIGN"],
    price: 240.0,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 7,
    shopId: 107,
    name: "Yard Butler Garden Kneeler and Seat",
    categoryId: 7,
    description:
      "The Yard Butler Garden Kneeler and Seat is a combination kneeling pad and outdoor stool. This folding, portable, lightweight garden stool has handles to assist users in sitting and standing.",
    benefits: [
      "COMBINATION KNEELING PAD AND SEAT",
      "FOLDING AND PORTABLE",
      "LIGHTWEIGHT",
    ],
    price: 70.0,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 8,
    shopId: 108,
    name: "Home Stair Lift",
    categoryId: 6,
    description:
      "The purpose of the accessibility home modification is to provide an accessible and safe environment while you are in your home.",
    benefits: ["SAFE AND ACCESSIBLE", "EASY INSTALLATION", "DURABLE"],
    price: 2000.0,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 9,
    shopId: 109,
    name: "Wheelchair Ramp",
    categoryId: 6,
    description:
      "Wheelchair ramps provide accessibility solutions for homes, vehicles, and businesses.",
    benefits: ["DURABLE MATERIAL", "EASY TO INSTALL", "SAFE AND RELIABLE"],
    price: 300.0,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 10,
    shopId: 110,
    name: "Electric Wheelchair",
    categoryId: 1,
    description:
      "Electric wheelchairs provide a convenient, reliable, and comfortable mobility solution.",
    benefits: ["COMFORTABLE SEATING", "LONG BATTERY LIFE", "EASY TO CONTROL"],
    price: 1500.0,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 11,
    shopId: 111,
    name: "Reacher Grabber Tool",
    categoryId: 2,
    description:
      "Reacher grabber tool allows users to pick up items without bending or stretching.",
    benefits: ["LIGHTWEIGHT", "EASY TO USE", "VERSATILE"],
    price: 25.0,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 12,
    shopId: 112,
    name: "Shower Chair",
    categoryId: 3,
    description: "Shower chairs provide stability and support while bathing.",
    benefits: ["NON-SLIP SEAT", "ADJUSTABLE HEIGHT", "STURDY AND DURABLE"],
    price: 50.0,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 13,
    shopId: 113,
    name: "Handheld Shower Head",
    categoryId: 3,
    description:
      "Handheld shower heads provide convenience and flexibility for individuals with limited mobility.",
    benefits: ["EASY TO INSTALL", "ADJUSTABLE SETTINGS", "DURABLE DESIGN"],
    price: 30.0,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 14,
    shopId: 114,
    name: "Portable Oxygen Concentrator",
    categoryId: 4,
    description:
      "Portable oxygen concentrators provide a continuous supply of oxygen for individuals with respiratory issues.",
    benefits: ["LIGHTWEIGHT AND PORTABLE", "LONG BATTERY LIFE", "EASY TO USE"],
    price: 1200.0,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 15,
    shopId: 115,
    name: "Hearing Aid",
    categoryId: 5,
    description:
      "Hearing aids amplify sound for individuals with hearing loss.",
    benefits: ["DISCREET DESIGN", "ADJUSTABLE SETTINGS", "LONG BATTERY LIFE"],
    price: 700.0,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 16,
    shopId: 116,
    name: "Braille Keyboard",
    categoryId: 5,
    description:
      "Braille keyboards allow visually impaired individuals to use computers and mobile devices.",
    benefits: [
      "EASY TO USE",
      "COMPATIBLE WITH MULTIPLE DEVICES",
      "DURABLE DESIGN",
    ],
    price: 350.0,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 17,
    shopId: 117,
    name: "Voice Activated Assistant",
    categoryId: 5,
    description:
      "Voice activated assistants provide hands-free control of smart home devices.",
    benefits: ["EASY TO SET UP", "COMPATIBLE WITH MANY DEVICES", "CONVENIENT"],
    price: 150.0,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 18,
    shopId: 118,
    name: "Magnifying Glass",
    categoryId: 2,
    description:
      "Magnifying glasses help individuals with low vision read and perform tasks.",
    benefits: ["LIGHTWEIGHT", "EASY TO USE", "VERSATILE"],
    price: 15.0,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 19,
    shopId: 119,
    name: "Adjustable Bed",
    categoryId: 1,
    description:
      "Adjustable beds provide comfort and support for individuals with medical needs.",
    benefits: ["ADJUSTABLE SETTINGS", "COMFORTABLE", "DURABLE"],
    price: 1000.0,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 20,
    shopId: 120,
    name: "Walk-in Bathtub",
    categoryId: 3,
    description:
      "Walk-in bathtubs provide safety and convenience for individuals with limited mobility.",
    benefits: ["EASY TO ENTER", "NON-SLIP SURFACE", "DURABLE DESIGN"],
    price: 2000.0,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 21,
    shopId: 121,
    name: "Lift Chair",
    categoryId: 1,
    description:
      "Lift chairs assist individuals in standing up from a seated position.",
    benefits: ["ADJUSTABLE SETTINGS", "COMFORTABLE", "DURABLE"],
    price: 700.0,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 22,
    shopId: 122,
    name: "Rollator Walker",
    categoryId: 1,
    description:
      "Rollator walkers provide stability and support for individuals with mobility issues.",
    benefits: ["LIGHTWEIGHT", "EASY TO USE", "DURABLE"],
    price: 150.0,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 23,
    shopId: 123,
    name: "Cane",
    categoryId: 1,
    description:
      "Canes provide support and balance for individuals with limited mobility.",
    benefits: ["LIGHTWEIGHT", "EASY TO USE", "DURABLE"],
    price: 25.0,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 24,
    shopId: 124,
    name: "Wheelchair",
    categoryId: 1,
    description:
      "Wheelchairs provide mobility and independence for individuals with limited mobility.",
    benefits: ["COMFORTABLE SEATING", "EASY TO MANEUVER", "DURABLE"],
    price: 500.0,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 25,
    shopId: 125,
    name: "Portable Ramp",
    categoryId: 6,
    description:
      "Portable ramps provide accessibility solutions for homes, vehicles, and businesses.",
    benefits: ["LIGHTWEIGHT", "EASY TO USE", "DURABLE"],
    price: 200.0,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 26,
    shopId: 126,
    name: "Transfer Bench",
    categoryId: 3,
    description:
      "Transfer benches provide stability and support while transferring in and out of the bathtub.",
    benefits: ["ADJUSTABLE HEIGHT", "NON-SLIP SURFACE", "DURABLE DESIGN"],
    price: 80.0,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 27,
    shopId: 127,
    name: "Handheld Magnifier",
    categoryId: 2,
    description:
      "Handheld magnifiers help individuals with low vision read and perform tasks.",
    benefits: ["LIGHTWEIGHT", "EASY TO USE", "VERSATILE"],
    price: 20.0,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 28,
    shopId: 128,
    name: "Adjustable Walking Cane",
    categoryId: 1,
    description:
      "Adjustable walking canes provide support and balance for individuals with limited mobility.",
    benefits: ["LIGHTWEIGHT", "ADJUSTABLE HEIGHT", "DURABLE"],
    price: 30.0,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 29,
    shopId: 129,
    name: "Mobility Scooter",
    categoryId: 1,
    description:
      "Mobility scooters provide a convenient and comfortable mobility solution.",
    benefits: ["EASY TO CONTROL", "COMFORTABLE SEATING", "LONG BATTERY LIFE"],
    price: 1200.0,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 30,
    shopId: 130,
    name: "Grab Bars",
    categoryId: 6,
    description:
      "Grab bars provide stability and support in bathrooms and other areas.",
    benefits: ["EASY TO INSTALL", "DURABLE", "SAFE"],
    price: 40.0,
    imageUrl: "https://via.placeholder.com/150",
  },
];

export default products;
